### ISSUE TITLE
Wrong case in GitHub URL in go sources

### ISSUE THREAD

**Issue by markusfisch** [DiSiqueira/coronabot#13]
On a case-sensitive file system (like ext4), getting your package with

```
$ go get github.com/DiSiqueira/coronabot
```

will result in `$GOPATH/go/src/github.com/DiSiqueira/coronabot` but the the Go sources reference `github.com/disiqueira/coronabot/...`. This means, `go run` will fail:

```
~/go/src/github.com/DiSiqueira/coronabot $ go run cmd/coronabot/main.go 
cmd/coronabot/main.go:14:2: cannot find package "github.com/disiqueira/coronabot
/internal/application" in any of:
...
```

A possible solution would be to rename all occurrences in the Go sources to `DiSiqueira` to match the original GitHub URL:
```
$ sed -i -s 's/disiqueira/DiSiqueira/g' $(fgrep -rl disiqueira *)
```

Or, if you're using BSD's `sed` (including macOS):
```
$ sed -i '' -s 's/disiqueira/DiSiqueira/g' $(fgrep -rl disiqueira *)
```

**Comment by d6o** [comment]
This shouldn't be an issue, the project is built using go 1.14 with modules, so it's not supposed to cloned inside GOPATH. 

To fix it, clone the project in another path outside GOPATH and have modules enabled.

Modules are enabled by default on the latest versions, but `export GO111MODULE=on` will do the trick on 1.11+. To make sure that you have it properly set, just run `go env | grep -i module` in the root folder after cloning it in another path. 

Please let me know if that fixes your problem.

**Comment by markusfisch** [comment]
Yes, cloning the repo somewhere else and setting `GO111MODULE` worked liked a charm 👍 

Thank you for the quick response.
